- type: static_site
  name: my-frontend
  buildCommand: cd Frontend && npm install && npm run build
  publishDirectory: Frontend/dist  # This is the directory where Vite stores the build output
  startCommand: cd Frontend && npx serve -s dist
  branch: main
  envVars:
    - key: REACT_APP_API_URL
      value: "https://devconnect-w1w6.onrender.com" # The backend API URL for production
  manualDeploy: true
  regions:
    - oregon
