services:
  - type: static
    name: my-frontend
    buildCommand: cd Frontend && npm install && npm run build
    publishDir: Frontend/dist
    staticPublishPath: /
    branch: main
    envVars:
      - key: VITE_API_URL
      value:https://devconnect-w1w6.onrender.com # The backend API URL for production
  manualDeploy: true
  regions:
    - oregon
