services:
  - type: web
    name: my-backend
    env: node
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && npm start
    branch: main
    envVars:
      - key: MONGO_URI
        value: "YOUR_PRODUCTION_MONGO_URI"
      - key: JWT_SECRET
        value: "YOUR_PRODUCTION_JWT_SECRET"
      - key: CLOUDINARY_CLOUD_NAME
        value: "YOUR_CLOUDINARY_CLOUD_NAME"
      - key: CLOUDINARY_API_KEY
        value: "YOUR_CLOUDINARY_API_KEY"
      - key: CLOUDINARY_API_SECRET
        value: "YOUR_CLOUDINARY_API_SECRET"
