services:
  - type: web
    name: my-backend
    env: node
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && npm start
    branch: main
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://devconnect-1-imto.onrender.com